### ISSUE TITLE
Base layer picker icon is broken

### ISSUE THREAD

**Issue by andre-carvalho** [terrabrasilis/ams#201]
File "layers-2x.png" missing from app/static/css/lib/leaflet/1.7.1/images/

In some OS/browser configurations, specific CSS class is used and background image is changed to leyers-2x which is missing from the repository.

```css
.leaflet-control-layers-toggle {
  background-image: url(images/layers.png);
  width: 36px;
  height: 36px;
}
.leaflet-retina .leaflet-control-layers-toggle {
  background-image: url(images/layers-2x.png);
  background-size: 26px 26px;
}
```

![Captura de tela de 2024-06-04 14-26-03](https://github.com/terrabrasilis/ams/assets/11821768/18c870c0-7b1d-4b21-b591-704f027f4062)
